<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Auction>
 */
class AuctionFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => 1, // Pastikan ada user dengan ID 1 di database
            'category_id' => 1, // Pastikan ada kategori dengan ID 1 di database
            'title' => 'Stress Test Asset ' . $this->faker->uuid(),
            'description' => 'Load testing data generated by factory.',
            'starting_price' => 10000,
            'current_price' => 10000,
            'start_time' => now()->subHour(),
            'end_time' => now()->addMinutes(rand(1, 5)), // Akan expired massal sebentar lagi
            'status' => 'active',
        ];
    }
}
